### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by itsmraga-hub** [michael-duke/Leaderboard#4]
# ⚠️ Issue No 1

- Hey @michael-duke, great work on your project, really impressive UI and UX. Keep honing your skills. However, we noticed some things that we'd like you to check on, they are optional so work on them on your own time.
    - Try to fix the responsiveness down to all devices.
    - This is just a personal preference but try to align the names and scores to appear on single straight lines for better UX.
    - In your JavaScript code, I'm seeing both localStorage and API calls that kinda perform the same role in your project: which is to store data. I think a better approach would be to make a single call to each depending on the availability of an internet connection. i.e. If there is an internet connection, fetch data from the API else fetch data from the localStorage.
    - Add live project screenshots to the README to make the project more accessible.

**Comment by michael-duke** [comment]
Thank you team for your review I have fixed most of the requests

**Comment by itsmraga-hub** [comment]
Good to hear @michael-duke. 🥂 and Happy coding.
